name: CI/CD Release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm ci

    - name: Bump version, generate changelog, commit and tag
      run: npm run release:ci

    - name: Push changes to repo
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master

    - name: Run tests
      run: npm run test

    - name: Build VSIX package
      run: npm run build

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $(git describe --tags --abbrev=0)
        name: Release $(git describe --tags --abbrev=0)
        body_path: CHANGELOG.md
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload VSIX asset to release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: $(git describe --tags --abbrev=0)
        files: ./path/to/your-extension.vsix
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}